trigger:
  branches:
    include:
    - dev
    - release-*

jobs:
- job:
  strategy:
    matrix:
      linux_s3:
        imageName: 'ubuntu-16.04'
        TILEDB_S3: ON
        TILEDB_STATIC: OFF
        CXX: g++
      linux_hdfs:
        imageName: 'ubuntu-16.04'
        TILEDB_HDFS: ON
        CXX: g++
      macOS:
        imageName: 'macOS-10.14'
        TILEDB_S3: ON
        CXX: clang++
      linux_asan:
        imageName: 'ubuntu-16.04'
        TILEDB_CI_ASAN: ON
        TILEDB_TBB: OFF
        CXX: g++-7
      linux_serialization:
        imageName: 'ubuntu-16.04'
        TILEDB_SERIALIZATION: ON
        TILEDB_S3: ON
        CXX: g++

  pool:
    vmImage: $(imageName)
  steps:
  - template: scripts/azure-linux_mac.yml

- job: CentOS6_manylinux1
  container:
    image: quay.io/pypa/manylinux1_x86_64
  variables:
    CXX: g++
    TILEDB_FORCE_BUILD_DEPS: ON
    TILEDB_BUILD_ENABLE: "s3,azure,serialization,static-tiledb"
  steps:
  - template: scripts/azure-centos6.yml

- job: Windows
  strategy:
    matrix:
      VS2017:
        imageName: 'vs2017-win2016'
        TILEDB_S3: ON
        TILEDB_TOOLS: ON
  pool:
    vmImage: $(imageName)
  steps:
  - template: scripts/azure-windows.yml
